import { Header } from "@/Layout/Header/Header";
import "../assets/styles/globals.css";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import { Footer } from "@/Layout/Footer";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});
const outfit = Outfit({
    subsets: ["latin"],
    variable: "--font-outfit",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${outfit.variable} text-primary-100 flex flex-col flex-1 relative`}>
                <Header />
                <main className="flex-1 mt-12">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
